#!/usr/bin/env python3

import os, csv, re, sys
from datetime import datetime, timedelta, timezone
from github import Github, Auth
from dotenv import load_dotenv
import requests_cache

# 1. Configuration du Cache (Données gardées 24h)
requests_cache.install_cache('github_api_cache', expire_after=86400)
sys.setrecursionlimit(5000)
load_dotenv()

token = os.getenv("GITHUB_TOKEN")
if not token:
    raise ValueError("GITHUB_TOKEN non defini dans .env")

g = Github(auth=Auth.Token(token), per_page=100)

# --- CHANGEMENT ICI : BEAUCOUP PLUS DE DONNÉES ---
LANGUAGES = ["typescript", "javascript", "python"]
MAX_REPOS_PER_LANGUAGE = 150  
MAX_PRS_PER_REPO = 300     
PR_CSV_FILE = "agile_pr_level.csv"
PROJECT_CSV_FILE = "agile_project_level.csv"

# Regex pour les Story Points
SP_LABEL_PATTERNS =[
    r"^sp[:\-\s]?(\d+)$", 
    r"^story[\-\s]?points?[:\-\s]?(\d+)$",
    r"^points?[:\-\s]?(\d+)$", 
    r"^size[:\-\s]?(xs|s|m|l|xl)$"
]
SIZE_MAP = {"xs": 1, "s": 2, "m": 3, "l": 5, "xl": 8}
FIBONACCI_VALID = {1, 2, 3, 5, 8, 13, 21, 34, 55}
AI_KEYWORDS =["copilot", "gpt", "llm", "openai", "claude", "cursor", "generated by"]

FIELDNAMES_PR =[
    "language", "repo_name", "pr_number", "story_points",
    "pre_coding_title", "pre_coding_description",
    "pre_coding_desc_length", "pre_coding_subtasks",
    "pre_coding_author_tenure_days", "pre_coding_discussion_participants",
    "is_ai_assisted",
    "post_coding_churn", "post_coding_cyclomatic_proxy", 
    "post_coding_test_coverage_ratio",
    "ai_mentions", "ai_generation_ratio", "ai_speed_proxy"
]

FIELDNAMES_PROJECT =[
    "language", "repo_name", "total_prs_analyzed", "total_story_points_project",
    "avg_pre_coding_desc_length", "total_post_coding_churn",
    "avg_ai_generation_ratio", "total_ai_mentions"
]

def clean_text(text):
    if not text: return ""
    return re.sub(r'\s+', ' ', text).strip()[:2000]

def extract_story_points(pr):
    for label in pr.labels:
        name = label.name.strip().lower()
        for pattern in SP_LABEL_PATTERNS:
            match = re.match(pattern, name)
            if match:
                val = match.group(1)
                points = SIZE_MAP[val] if val in SIZE_MAP else int(val)
                return min(FIBONACCI_VALID, key=lambda x: abs(x - points))
    return None

def extract_pre_coding_features(pr):
    title = clean_text(pr.title)
    body = clean_text(pr.body)
    
    desc_length = len(pr.body or "")
    subtasks = (pr.body or "").count("- [ ]") + (pr.body or "").count("- [x]")
    tenure_days = 0
    if pr.user:
        try:
            tenure_days = (pr.created_at - pr.user.created_at).days
        except Exception:
            tenure_days = 0
    
    try: 
        participants = len(set(c.user.login for c in pr.get_issue_comments() if c.user))
    except: 
        participants = 1

    return title, body, desc_length, subtasks, max(tenure_days, 0), max(participants, 1)

def extract_post_and_ai_features(pr):
    churn = pr.additions + pr.deletions
    if churn == 0: return 0, 0, 0, 0, 0, 0, 0

    ai_gen_ratio = round(pr.additions / (pr.deletions + 1), 2)
    ai_mentions = 0
    ai_speed_proxy = 0
    is_ai_assisted = 0 

    try:
        commits = list(pr.get_commits())
        for c in commits:
            if any(kw in c.commit.message.lower() for kw in AI_KEYWORDS):
                ai_mentions += 1
                is_ai_assisted = 1 
        
        if len(commits) > 1:
            first_time = commits[0].commit.author.date
            last_time = commits[-1].commit.author.date
            commit_duration = max((last_time - first_time).total_seconds() / 60, 1)
            ai_speed_proxy = round(churn / commit_duration, 2)
    except: pass

    if is_ai_assisted == 0 and ai_gen_ratio > 10 and churn > 300:
        is_ai_assisted = 1

    cyclo_complexity, test_lines, src_lines = 0, 0, 0
    try:
        for f in pr.get_files():
            fname = f.filename.lower()
            if 'test' in fname: test_lines += f.additions
            elif fname.endswith(('.py', '.js', '.ts')): 
                src_lines += f.additions
                if f.patch:
                    for line in f.patch.split('\n'):
                        if line.startswith('+') and re.search(r'\b(if|else|for|while|try)\b', line):
                            cyclo_complexity += 1
    except: pass

    test_coverage = round(test_lines / src_lines, 4) if src_lines > 0 else 0.0

    return churn, cyclo_complexity, test_coverage, ai_mentions, ai_gen_ratio, ai_speed_proxy, is_ai_assisted

def extract_data():
    repos_traites = set() 
    one_month_ago = datetime.now(timezone.utc) - timedelta(days=30)
    
    with open(PR_CSV_FILE, "w", newline="", encoding="utf-8") as fpr, \
         open(PROJECT_CSV_FILE, "w", newline="", encoding="utf-8") as fproj:
        
        writer_pr = csv.DictWriter(fpr, fieldnames=FIELDNAMES_PR, quoting=csv.QUOTE_MINIMAL)
        writer_proj = csv.DictWriter(fproj, fieldnames=FIELDNAMES_PROJECT)
        writer_pr.writeheader()
        writer_proj.writeheader()

        repo_idx = 0
        
        for language in LANGUAGES:
            print(f"\nAnalyse du langage : {language}\n")
            
            repos_search = g.search_repositories(
                query=f"language:{language} stars:>1000 fork:false", 
                sort="stars", 
                order="desc"
            )
            
            language_repo_count = 0
            
            for repo in repos_search:
                if language_repo_count >= MAX_REPOS_PER_LANGUAGE:
                    print(f"Limite atteinte pour {language}")
                    break
                if repo.full_name in repos_traites:
                    continue 
                
                try:
                    if not any(any(re.match(p, l.name.lower()) for p in SP_LABEL_PATTERNS) for l in repo.get_labels()): 
                        continue

                    print(f"[+] Projet {repo_idx+1} ({language}) : {repo.full_name}...")
                    
                    try:
                        prs = repo.get_pulls(state='closed', sort='updated', direction='desc')
                        proj_sp, proj_desc, proj_churn, proj_ai_gen, proj_ai_mentions, pr_count = 0, 0, 0, 0, 0, 0

                        for pr in prs:
                            if pr_count >= MAX_PRS_PER_REPO:
                                break
                            
                            if not pr or not pr.merged_at:
                                continue
                            if pr.merged_at < one_month_ago:
                                continue

                            sp = extract_story_points(pr)
                            if sp is None:
                                continue

                            title, desc, desc_len, subtasks, tenure, participants = extract_pre_coding_features(pr)
                            churn, cyclo, test_cov, ai_mentions, ai_gen, ai_speed, is_ai = extract_post_and_ai_features(pr)

                            if churn == 0:
                                continue

                            writer_pr.writerow({
                                "language": language,
                                "repo_name": repo.name, "pr_number": pr.number, "story_points": sp,
                                "pre_coding_title": title, "pre_coding_description": desc,
                                "pre_coding_desc_length": desc_len, "pre_coding_subtasks": subtasks,
                                "pre_coding_author_tenure_days": tenure, "pre_coding_discussion_participants": participants,
                                "is_ai_assisted": is_ai,
                                "post_coding_churn": churn, "post_coding_cyclomatic_proxy": cyclo, 
                                "post_coding_test_coverage_ratio": test_cov,
                                "ai_mentions": ai_mentions, "ai_generation_ratio": ai_gen, "ai_speed_proxy": ai_speed
                            })
                            
                            proj_sp += sp
                            proj_desc += desc_len
                            proj_churn += churn
                            proj_ai_gen += ai_gen
                            proj_ai_mentions += ai_mentions
                            pr_count += 1
                            print(f"    PR #{pr.number} (SP:{sp}) | IA: {'Oui' if is_ai else 'Non'}")

                        if pr_count > 0:
                            writer_proj.writerow({
                                "language": language,
                                "repo_name": repo.name, "total_prs_analyzed": pr_count,
                                "total_story_points_project": proj_sp, 
                                "avg_pre_coding_desc_length": round(proj_desc / pr_count, 2),
                                "total_post_coding_churn": proj_churn,
                                "avg_ai_generation_ratio": round(proj_ai_gen / pr_count, 2),
                                "total_ai_mentions": proj_ai_mentions
                            })
                            repo_idx += 1
                            language_repo_count += 1
                            fpr.flush()
                            fproj.flush()
                    
                    except Exception as e:
                        print(f" [!] Erreur lors de l'accès aux PRs de {repo.full_name}: {e}")
                        continue

                except Exception as e:
                    print(f" [!] Erreur générale sur le repo {repo.full_name}: {e}")
                    continue
                
                repos_traites.add(repo.full_name)

    print(f"\nTERMINÉ ! {repo_idx} projets analysés au total.")

if __name__ == "__main__":
    extract_data()