#!/usr/bin/env python3

import os, csv, re, sys
from datetime import datetime, timedelta, timezone
from github import Github, Auth
from dotenv import load_dotenv
import requests_cache

# 1. Configuration du Cache (Données gardées 24h)
requests_cache.install_cache('github_api_cache', expire_after=86400)
sys.setrecursionlimit(5000)
load_dotenv()

token = os.getenv("GITHUB_TOKEN")
if not token:
    raise ValueError("GITHUB_TOKEN non defini dans .env")

g = Github(auth=Auth.Token(token), per_page=100)

# CONFIGURATION
LANGUAGE = "python"
MAX_REPOS = 100       
MAX_PRS_PER_REPO = 30     
PR_CSV_FILE = "agile_pr_level.csv"
PROJECT_CSV_FILE = "agile_project_level.csv"

# Regex pour les Story Points
SP_LABEL_PATTERNS =[
    r"^sp[:\-\s]?(\d+)$", 
    r"^story[\-\s]?points?[:\-\s]?(\d+)$",
    r"^points?[:\-\s]?(\d+)$", 
    r"^size[:\-\s]?(xs|s|m|l|xl)$"
]
SIZE_MAP = {"xs": 1, "s": 2, "m": 3, "l": 5, "xl": 8}
FIBONACCI_VALID = {1, 2, 3, 5, 8, 13, 21, 34, 55}
AI_KEYWORDS =["copilot", "gpt", "llm", "openai", "claude", "cursor", "generated by"]

FIELDNAMES_PR =[
    "repo_name", "pr_number", "story_points",
    # --- FEATURES A PRIORI (Pour prédire les Story Points) ---
    "pre_coding_title", "pre_coding_description",
    "pre_coding_desc_length", "pre_coding_subtasks",
    "pre_coding_author_tenure_days", "pre_coding_discussion_participants",
    
    # --- NOUVEAU : LA VARIABLE TEMPS (Cible pour prédire les heures) ---
    "actual_duration_hours", 
    "is_ai_assisted", # <-- Flag Binaire (1 ou 0) très utile pour le ML
    
    # --- FEATURES A POSTERIORI & IA DÉTAILLÉES (Audit) ---
    "post_coding_churn", "post_coding_cyclomatic_proxy", 
    "post_coding_test_coverage_ratio",
    "ai_mentions", "ai_generation_ratio", "ai_speed_proxy"
]

FIELDNAMES_PROJECT =[
    "repo_name", "total_prs_analyzed", "total_story_points_project",
    "total_duration_hours_project", # <-- Temps total du projet
    "avg_pre_coding_desc_length", "total_post_coding_churn",
    "avg_ai_generation_ratio", "total_ai_mentions"
]

def clean_text(text):
    if not text: return ""
    return re.sub(r'\s+', ' ', text).strip()[:2000]

def extract_story_points(pr):
    for label in pr.labels:
        name = label.name.strip().lower()
        for pattern in SP_LABEL_PATTERNS:
            match = re.match(pattern, name)
            if match:
                val = match.group(1)
                points = SIZE_MAP[val] if val in SIZE_MAP else int(val)
                return min(FIBONACCI_VALID, key=lambda x: abs(x - points))
    return None

def extract_pre_coding_features(pr):
    title = clean_text(pr.title)
    body = clean_text(pr.body)
    
    desc_length = len(pr.body or "")
    subtasks = (pr.body or "").count("- [ ]") + (pr.body or "").count("- [x]")
    tenure_days = 0
    if pr.user:
        try:
            tenure_days = (pr.created_at - pr.user.created_at).days
        except Exception:
            tenure_days = 0
    
    try: 
        participants = len(set(c.user.login for c in pr.get_issue_comments() if c.user))
    except: 
        participants = 1

    return title, body, desc_length, subtasks, max(tenure_days, 0), max(participants, 1)

def extract_post_and_ai_features(pr):
    # CALCUL DU TEMPS RÉEL
    created = pr.created_at
    merged = pr.merged_at
    duration_hours = max((merged - created).total_seconds() / 3600, 0.5)

    churn = pr.additions + pr.deletions
    if churn == 0: return 0, 0, 0, 0, 0, 0, round(duration_hours, 2), 0

    ai_gen_ratio = round(pr.additions / (pr.deletions + 1), 2)
    ai_mentions = 0
    ai_speed_proxy = 0
    is_ai_assisted = 0 # Par défaut Non

    try:
        commits = list(pr.get_commits())
        for c in commits:
            if any(kw in c.commit.message.lower() for kw in AI_KEYWORDS):
                ai_mentions += 1
                is_ai_assisted = 1 # On est sûr que l'IA a été utilisée
        
        if len(commits) > 1:
            first_time = commits[0].commit.author.date
            last_time = commits[-1].commit.author.date
            commit_duration = max((last_time - first_time).total_seconds() / 60, 1)
            ai_speed_proxy = round(churn / commit_duration, 2)
    except: pass

    # Règle de suspicion si comportement robotique massif
    if is_ai_assisted == 0 and ai_gen_ratio > 10 and churn > 300:
        is_ai_assisted = 1

    cyclo_complexity, test_lines, src_lines = 0, 0, 0
    try:
        for f in pr.get_files():
            fname = f.filename.lower()
            if 'test' in fname: test_lines += f.additions
            elif fname.endswith(('.py', '.js', '.ts')): 
                src_lines += f.additions
                if f.patch:
                    for line in f.patch.split('\n'):
                        if line.startswith('+') and re.search(r'\b(if|else|for|while|try)\b', line):
                            cyclo_complexity += 1
    except: pass

    test_coverage = round(test_lines / src_lines, 4) if src_lines > 0 else 0.0

    return churn, cyclo_complexity, test_coverage, ai_mentions, ai_gen_ratio, ai_speed_proxy, round(duration_hours, 2), is_ai_assisted

def extract_data():
    # 1. On crée un ensemble pour suivre les dépôts déjà traités pendant cette session
    repos_traites = set() 
    
    six_months_ago = datetime.now(timezone.utc) - timedelta(days=180)
    repos_search = g.search_repositories(query=f"language:{LANGUAGE} stars:>1000 fork:false", sort="stars", order="desc")
    # On utilise "w" pour repartir sur un fichier propre à chaque lancement
    with open(PR_CSV_FILE, "w", newline="", encoding="utf-8") as fpr, \
         open(PROJECT_CSV_FILE, "w", newline="", encoding="utf-8") as fproj:
        
        writer_pr = csv.DictWriter(fpr, fieldnames=FIELDNAMES_PR, quoting=csv.QUOTE_MINIMAL)
        writer_proj = csv.DictWriter(fproj, fieldnames=FIELDNAMES_PROJECT)
        
        # Comme on est en mode "w", on écrit l'en-tête systématiquement
        writer_pr.writeheader()
        writer_proj.writeheader()

        repo_idx = 0
        for repo in repos_search:
            # --- VERIFICATION DES DOUBLONS ICI ---
            if repo.full_name in repos_traites:
                continue # On passe au suivant s'il est déjà là
            
            if repo_idx >= MAX_REPOS: break
            
            # Vérification si le repo utilise des Story Points
            try:
                if not any(any(re.match(p, l.name.lower()) for p in SP_LABEL_PATTERNS) for l in repo.get_labels()): 
                    continue
            except: continue

            # Marquer le repo comme "vu" pour ne plus le traiter
            repos_traites.add(repo.full_name)

            print(f"\n[+] Analyse du Projet {repo_idx+1}/{MAX_REPOS} : {repo.full_name}...")
            prs = repo.get_pulls(state='closed', sort='updated', direction='desc')
            
            proj_sp, proj_hours, proj_desc, proj_churn, proj_ai_gen, proj_ai_mentions, pr_count = 0, 0, 0, 0, 0, 0, 0

            for pr in prs:
                if pr_count >= MAX_PRS_PER_REPO: break
                if not pr.merged_at or pr.merged_at < six_months_ago: continue

                sp = extract_story_points(pr)
                if sp is None: continue

                title, desc, desc_len, subtasks, tenure, participants = extract_pre_coding_features(pr)
                churn, cyclo, test_cov, ai_mentions, ai_gen, ai_speed, dur_hours, is_ai = extract_post_and_ai_features(pr)

                if churn == 0: continue

                writer_pr.writerow({
                    "repo_name": repo.name, "pr_number": pr.number, "story_points": sp,
                    "pre_coding_title": title, "pre_coding_description": desc,
                    "pre_coding_desc_length": desc_len, "pre_coding_subtasks": subtasks,
                    "pre_coding_author_tenure_days": tenure, "pre_coding_discussion_participants": participants,
                    
                    "actual_duration_hours": dur_hours,  # <-- Les heures ajoutées ici
                    "is_ai_assisted": is_ai,             # <-- Oui/Non (1 ou 0)
                    
                    "post_coding_churn": churn, "post_coding_cyclomatic_proxy": cyclo, 
                    "post_coding_test_coverage_ratio": test_cov,
                    "ai_mentions": ai_mentions, "ai_generation_ratio": ai_gen, "ai_speed_proxy": ai_speed
                })
                
                proj_sp += sp
                proj_hours += dur_hours
                proj_desc += desc_len
                proj_churn += churn
                proj_ai_gen += ai_gen
                proj_ai_mentions += ai_mentions
                pr_count += 1
                
                print(f"    PR #{pr.number} (SP:{sp}) | IA: {'Oui' if is_ai else 'Non'} | Temps: {dur_hours}h")

            if pr_count > 0:
                writer_proj.writerow({
                    "repo_name": repo.name, "total_prs_analyzed": pr_count,
                    "total_story_points_project": proj_sp, 
                    "total_duration_hours_project": round(proj_hours, 2), # <-- Le temps total du projet
                    "avg_pre_coding_desc_length": round(proj_desc / pr_count, 2),
                    "total_post_coding_churn": proj_churn,
                    "avg_ai_generation_ratio": round(proj_ai_gen / pr_count, 2),
                    "total_ai_mentions": proj_ai_mentions
                })
                repo_idx += 1
                fpr.flush(); fproj.flush()

    print(f"\nTerminé ! Données sauvegardées.")

if __name__ == "__main__":
    extract_data()