from github import Github, Auth
from dotenv import load_dotenv
from datetime import datetime, timedelta, timezone
import os, csv, time, re
import sys

# Augmenter la limite pour éviter l'erreur sur les très gros dépôts
sys.setrecursionlimit(5000) 

load_dotenv()
token = os.getenv("GITHUB_TOKEN")
g = Github(auth=Auth.Token(token), per_page=100)

LANGUAGE = "python"
MAX_REPOS = 10
MAX_PRS_PER_REPO = 30
CSV_FILE = "agile_raw_data.csv"
AI_KEYWORDS = ["copilot", "gpt", "llm", "openai", "claude", "cursor", "generated by"]

SP_LABEL_PATTERNS = [
    r"^sp[:\-\s]?(\d+)$",           
    r"^story[\-\s]?points?[:\-\s]?(\d+)$",  
    r"^points?[:\-\s]?(\d+)$",      
    r"^(\d+)[:\-\s]?sp$",           
    r"^estimate[:\-\s]?(\d+)$",     
    r"^size[:\-\s]?(xs|s|m|l|xl)$", 
]

SIZE_MAP = {"xs": 1, "s": 2, "m": 3, "l": 5, "xl": 8}

fieldnames = [
    "repo_name", "pr_number", "story_points", "code_churn", "files_changed",
    "review_cycles", "pr_comments", "refactoring_ratio", "commit_velocity",
    "velocity_sprint", "active_contributors", "stars", "ai_mentions",
    "ai_commits"
]

def has_agile_labels(repo):
    """Vérifie rapidement si le repo utilise des labels de Story Points."""
    try:
        labels = repo.get_labels()
        for l in labels:
            name = l.name.lower()
            if any(re.match(p, name) for p in SP_LABEL_PATTERNS):
                return True
    except:
        pass
    return False

def extract_story_points(pr):
    for label in pr.labels:
        name = label.name.strip().lower()
        for pattern in SP_LABEL_PATTERNS:
            match = re.match(pattern, name)
            if match:
                value = match.group(1)
                if value in SIZE_MAP: return SIZE_MAP[value]
                try: return int(value)
                except: pass
    return None

def get_ai_signals(pr):
    content = f"{pr.title} {pr.body}".lower() if pr.body else pr.title.lower()
    mentions = sum(1 for kw in AI_KEYWORDS if kw in content)
    ai_commits = 0
    try:
        # On limite aux 20 derniers commits pour ne pas bloquer
        commits = pr.get_commits()
        for i, c in enumerate(commits):
            if i > 20: break 
            if any(kw in c.commit.message.lower() for kw in AI_KEYWORDS):
                ai_commits += 1
    except: pass
    return mentions, ai_commits

def get_data():
    now = datetime.now(timezone.utc)
    six_months_ago = now - timedelta(days=180)
    three_months_ago = now - timedelta(days=90)

    # CORRECTION ICI : Appel effectif de g.search_repositories
    query = f"language:{LANGUAGE} stars:>1000 fork:false -topic:awesome -topic:list"
    print(f"Recherche de dépôts avec la requête : {query}")
    repos_search = g.search_repositories(query=query, sort="stars", order="desc")

    repo_count = 0
    with open(CSV_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for repo in repos_search:
            if repo_count >= MAX_REPOS: break
            
            try:
                # Éviter les dépôts de type "liste" ou sans labels Agile
                if any(x in repo.name.lower() for x in ["list", "api", "awesome"]):
                    continue
                
                print(f"\nExamen de {repo.full_name}...")
                if not has_agile_labels(repo):
                    print("  > Ignoré : aucun label de Story Points trouvé.")
                    continue

                print(f"[{repo_count+1}/{MAX_REPOS}] Analyse approfondie de {repo.full_name}...")

                # 1. Stats Contributeurs (Sécurisé contre la récursion)
                active_contributors = 0
                try:
                    stats = repo.get_stats_contributors()
                    if stats:
                        for s in stats:
                            if s.weeks and s.weeks[-1].w > six_months_ago and s.total > 5:
                                active_contributors += 1
                    else: active_contributors = 1
                except:
                    active_contributors = 1

                try:
                    recent_count = repo.get_commits(since=three_months_ago).totalCount
                    velocity_sprint = round((recent_count / 90) * 14, 2)
                except: velocity_sprint = 0.0

                # 2. Analyse des Pull Requests
                prs = repo.get_pulls(state='closed', sort='updated', direction='desc')
                pr_collected = 0

                for pr in prs:
                    if pr_collected >= MAX_PRS_PER_REPO: break
                    if not pr.merged_at or pr.merged_at < six_months_ago: continue

                    story_points = extract_story_points(pr)
                    if story_points is None: continue 

                    ai_mentions, ai_commits = get_ai_signals(pr)
                    churn = pr.additions + pr.deletions
                    if churn < 5: continue

                    refactor_ratio = round(pr.deletions / churn, 4) if churn > 0 else 0
                    duration_hours = max((pr.merged_at - pr.created_at).total_seconds() / 3600, 1)

                    review_cycles = 0
                    try:
                        for r in pr.get_reviews():
                            if r.state == "CHANGES_REQUESTED": review_cycles += 1
                    except: pass

                    writer.writerow({
                        "repo_name": repo.name,
                        "pr_number": pr.number,
                        "story_points": story_points,
                        "code_churn": churn,
                        "files_changed": pr.changed_files,
                        "review_cycles": review_cycles,
                        "pr_comments": pr.comments + pr.review_comments,
                        "refactoring_ratio": refactor_ratio,
                        "commit_velocity": round(churn / duration_hours, 2),
                        "velocity_sprint": velocity_sprint,
                        "active_contributors": active_contributors,
                        "stars": repo.stargazers_count,
                        "ai_mentions": ai_mentions,
                        "ai_commits": ai_commits
                    })
                    pr_collected += 1
                    print(f"  > PR #{pr.number} collectée (SP: {story_points})")

                if pr_collected > 0:
                    repo_count += 1
                time.sleep(2) # Pause pour éviter le Rate Limit
                
            except Exception as e:
                print(f"Erreur sur {repo.full_name}: {e}")

    print(f"\nTerminé ! Fichier : {CSV_FILE}")

if __name__ == "__main__":
    get_data()