import pandas as pd
import joblib
from xgboost import XGBRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np
from github import Github, Auth
import os


CSV_FILE  = "agile_raw_data.csv"
MODEL_XGB = "sp_model_xgb.pkl"
MODEL_RF  = "sp_model_rf.pkl"

FEATURES = [
    "code_churn", "files_changed", "review_cycles", "pr_comments",
    "refactoring_ratio", "commit_velocity", "duration_hours",
    "ai_mentions", "ai_commits", "active_contributors"
]

FIBONACCI = [1, 2, 3, 5, 8, 13]

AI_KEYWORDS = ["copilot", "gpt", "llm", "openai", "claude", "cursor", "generated by"]

def load_data():
    df = pd.read_csv(CSV_FILE)
    df = df.dropna(subset=["story_points"])
    print(f"Dataset : {len(df)} PRs taggées chargées")
    X = df[FEATURES]
    y = df["story_points"]
    return X, y

def compute_metrics(y_true, y_pred, X, model, label):
    mae  = mean_absolute_error(y_true, y_pred)
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    r2   = r2_score(y_true, y_pred)
    errors = y_true.values - y_pred

    cv_mae  = -cross_val_score(model, X, y_true, cv=5, scoring="neg_mean_absolute_error").mean()
    cv_rmse = np.sqrt(-cross_val_score(model, X, y_true, cv=5, scoring="neg_mean_squared_error").mean())

    within_1sp = np.mean(np.abs(errors) <= 1) * 100  # % de PRs avec erreur ≤ 1 SP
    within_2sp = np.mean(np.abs(errors) <= 2) * 100  # % de PRs avec erreur ≤ 2 SP

    return {
        "label"     : label,
        "mae_test"  : mae,
        "rmse_test" : rmse,
        "r2"        : r2,
        "cv_mae"    : cv_mae,
        "cv_rmse"   : cv_rmse,
        "within_1sp": within_1sp,
        "within_2sp": within_2sp,
        "errors"    : errors,
    }

def print_metrics(m):
    print(f"\n── {m['label']} ─────────────────────────────")
    print(f"  MAE  test       : {m['mae_test']:.2f} SP   (cross-val: {m['cv_mae']:.2f})")
    print(f"  RMSE test       : {m['rmse_test']:.2f} SP   (cross-val: {m['cv_rmse']:.2f})")
    print(f"  R²              : {m['r2']:.3f}  {'(bon)' if m['r2'] > 0.7 else '(faible)'}")
    print(f"  Erreur ≤ 1 SP   : {m['within_1sp']:.1f}% des PRs")
    print(f"  Erreur ≤ 2 SP   : {m['within_2sp']:.1f}% des PRs")
    e = m["errors"]
    print(f"  Erreur min/max  : {e.min():.1f} / {e.max():.1f} SP")
    print(f"  Biais moyen     : {e.mean():.2f} SP  {'(sous-estime)' if e.mean() < 0 else '(sur-estime)'}")

def print_comparison(m_xgb, m_rf):
    cols = [
        ("MAE test",    "mae_test",   "{:.2f}"),
        ("RMSE test",   "rmse_test",  "{:.2f}"),
        ("R²",          "r2",         "{:.3f}"),
        ("CV MAE",      "cv_mae",     "{:.2f}"),
        ("CV RMSE",     "cv_rmse",    "{:.2f}"),
        ("≤ 1 SP (%)",  "within_1sp", "{:.1f}"),
        ("≤ 2 SP (%)",  "within_2sp", "{:.1f}"),
    ]
    print("\n── Comparaison ────────────────────────────────────────")
    print(f"  {'Métrique':<16} {'XGBoost':>10} {'Random Forest':>14} {'Gagnant':>10}")
    print(f"  {'─'*16} {'─'*10} {'─'*14} {'─'*10}")
    for name, key, fmt in cols:
        vx = m_xgb[key]
        vr = m_rf[key]
        # Pour MAE/RMSE/CV : plus petit = mieux ; pour R²/within : plus grand = mieux
        if key in ("r2", "within_1sp", "within_2sp"):
            winner = "XGBoost" if vx >= vr else "RF"
        else:
            winner = "XGBoost" if vx <= vr else "RF"
        sx = fmt.format(vx)
        sr = fmt.format(vr)
        print(f"  {name:<16} {sx:>10} {sr:>14} {winner:>10}")

def print_feature_importance(model, label):
    print(f"\n── Feature importance ({label}) ────────────")
    importances = sorted(zip(FEATURES, model.feature_importances_), key=lambda x: -x[1])
    for feat, imp in importances:
        bar = "█" * int(imp * 40)
        print(f"  {feat:<25} {bar} {imp:.3f}")

def train(X, y):
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # ── XGBoost ──
    xgb = XGBRegressor(
        n_estimators=300,
        learning_rate=0.05,
        max_depth=4,
        subsample=0.8,
        colsample_bytree=0.8,
        random_state=42,
        eval_metric="mae"
    )
    xgb.fit(X_train, y_train, eval_set=[(X_test, y_test)], verbose=False)
    m_xgb = compute_metrics(y_test, xgb.predict(X_test), X, xgb, "XGBoost")

    # ── Random Forest ──
    rf = RandomForestRegressor(n_estimators=200, random_state=42)
    rf.fit(X_train, y_train)
    m_rf = compute_metrics(y_test, rf.predict(X_test), X, rf, "Random Forest")

    # ── Métriques détaillées ──
    print_metrics(m_xgb)
    print_metrics(m_rf)

    # ── Tableau comparatif ──
    print_comparison(m_xgb, m_rf)

    # ── Feature importance ──
    print_feature_importance(xgb, "XGBoost")
    print_feature_importance(rf,  "Random Forest")

    # ── Vainqueur sur CV MAE ──
    winner = "XGBoost" if m_xgb["cv_mae"] <= m_rf["cv_mae"] else "Random Forest"
    print(f"\nMeilleur modèle (CV MAE) : {winner}")

    # ── Sauvegarde ──
    joblib.dump(xgb, MODEL_XGB)
    joblib.dump(rf,  MODEL_RF)
    print(f"Modèles sauvegardés → {MODEL_XGB} | {MODEL_RF}")

    return xgb if winner == "XGBoost" else rf

# ── 3. PRÉDICTION TEMPS RÉEL ───────────────────────────────────────────────────

def predict_sp(repo_name: str, pr_number: int, model_path: str = MODEL_XGB) -> dict:
    model = joblib.load(model_path)
    g     = Github(auth=Auth.Token(os.getenv("GITHUB_TOKEN")))
    repo  = g.get_repo(repo_name)
    pr    = repo.get_pull(pr_number)

    churn          = pr.additions + pr.deletions
    duration_hours = max((pr.updated_at - pr.created_at).total_seconds() / 3600, 1)

    review_cycles = 0
    try:
        for r in pr.get_reviews():
            if r.state == "CHANGES_REQUESTED":
                review_cycles += 1
    except:
        pass

    content     = f"{pr.title} {pr.body or ''}".lower()
    ai_mentions = sum(1 for kw in AI_KEYWORDS if kw in content)

    features = [[
        churn,
        pr.changed_files,
        review_cycles,
        pr.comments + pr.review_comments,
        round(pr.deletions / churn, 4) if churn > 0 else 0,
        round(churn / duration_hours, 2),
        round(duration_hours, 2),
        ai_mentions,
        0,   # ai_commits — coûteux en temps réel
        1    # active_contributors — valeur neutre
    ]]

    sp_raw     = model.predict(features)[0]
    sp_rounded = min(FIBONACCI, key=lambda x: abs(x - sp_raw))

    result = {
        "pr"          : f"#{pr_number} — {pr.title}",
        "sp_brut"     : round(float(sp_raw), 1),
        "sp_suggéré"  : sp_rounded,
        "churn"       : churn,
        "files"       : pr.changed_files,
        "durée_h"     : round(duration_hours, 1),
        "ai_mentions" : ai_mentions,
    }

    print("\n── Prédiction ─────────────────────────────")
    for k, v in result.items():
        print(f"  {k:<15} {v}")

    return result

# ── MAIN ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    X, y  = load_data()
    model = train(X, y)

    