from github import Github, Auth
from dotenv import load_dotenv
from datetime import datetime, timedelta, timezone
import os, csv, time, re

load_dotenv()
token = os.getenv("GITHUB_TOKEN")
g = Github(auth=Auth.Token(token), per_page=100)

LANGUAGE = "python"
MAX_REPOS = 10
MAX_PRS_PER_REPO = 30
CSV_FILE = "agile_raw_data.csv"
AI_KEYWORDS = ["copilot", "gpt", "llm", "openai", "claude", "cursor", "generated by"]

# Patterns pour extraire les story points depuis les labels/tags
SP_LABEL_PATTERNS = [
    r"^sp[:\-\s]?(\d+)$",           # sp:3, sp-3, sp 3, sp3
    r"^story[\-\s]?points?[:\-\s]?(\d+)$",  # story-points:5, story points 5
    r"^points?[:\-\s]?(\d+)$",      # points:8, point:2
    r"^(\d+)[:\-\s]?sp$",           # 3:sp, 3sp
    r"^estimate[:\-\s]?(\d+)$",     # estimate:5
    r"^size[:\-\s]?(xs|s|m|l|xl)$", # size:M (converti en points)
]

SIZE_MAP = {"xs": 1, "s": 2, "m": 3, "l": 5, "xl": 8}  # T-shirt sizes → points

fieldnames = [
    "repo_name", "pr_number", "story_points", "code_churn", "files_changed",
    "review_cycles", "pr_comments", "refactoring_ratio", "commit_velocity",
    "velocity_sprint", "active_contributors", "stars", "ai_mentions",
    "ai_commits"
]

def extract_story_points(pr):
    """Extrait les story points depuis les labels/tags de la PR uniquement."""
    for label in pr.labels:
        name = label.name.strip().lower()
        for pattern in SP_LABEL_PATTERNS:
            match = re.match(pattern, name)
            if match:
                value = match.group(1)
                # Cas taille T-shirt
                if value in SIZE_MAP:
                    return SIZE_MAP[value]
                try:
                    return int(value)
                except ValueError:
                    pass
    return None  # Pas de story points trouvés = on skip cette PR

def get_ai_signals(pr):
    """Scan des titres, corps et messages de commits pour détecter l'IA."""
    content = f"{pr.title} {pr.body}".lower() if pr.body else pr.title.lower()
    mentions = sum(1 for kw in AI_KEYWORDS if kw in content)
    ai_commits = 0
    try:
        for c in pr.get_commits():
            if any(kw in c.commit.message.lower() for kw in AI_KEYWORDS):
                ai_commits += 1
    except:
        pass
    return mentions, ai_commits

def get_data():
    now = datetime.now(timezone.utc)
    six_months_ago = now - timedelta(days=180)
    three_months_ago = now - timedelta(days=90)

    print("Recherche de dépôts populaires...")
    repos = g.search_repositories(query=f"language:{LANGUAGE} stars:>1000 fork:false")
    repo_count = 0

    with open(CSV_FILE, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for repo in repos:
            if repo_count >= MAX_REPOS:
                break
            try:
                print(f"\n[{repo_count+1}/{MAX_REPOS}] Analyse de {repo.full_name}...")

                # 1. Contexte du Repo
                active_contributors = 0
                stats = repo.get_stats_contributors()
                if stats:
                    for s in stats:
                        if s.weeks[-1].w > six_months_ago and s.total > 5:
                            active_contributors += 1
                else:
                    active_contributors = 1

                try:
                    recent_count = repo.get_commits(since=three_months_ago).totalCount
                    velocity_sprint = round((recent_count / 90) * 14, 2)
                except:
                    velocity_sprint = 0.0

                # 2. Analyse des Pull Requests
                prs = repo.get_pulls(state='closed', sort='updated', direction='desc')
                pr_collected = 0

                for pr in prs:
                    if pr_collected >= MAX_PRS_PER_REPO:
                        break
                    if not pr.merged_at:
                        continue

                    # Story points extraits des labels — variable cible
                    story_points = extract_story_points(pr)
                    if story_points is None:
                        continue  # On ignore les PRs sans story points taggés

                    # Détection IA par contenu (plus par période temporelle)
                    ai_mentions, ai_commits = get_ai_signals(pr)

                    # Métriques de code
                    churn = pr.additions + pr.deletions
                    if churn < 5:
                        continue  # On ignore les micro-fixes

                    refactor_ratio = round(pr.deletions / churn, 4) if churn > 0 else 0
                    
                    # Calcul interne pour commit_velocity (non exporté)
                    duration_hours = max((pr.merged_at - pr.created_at).total_seconds() / 3600, 1)

                    # Review cycles
                    review_cycles = 0
                    try:
                        for r in pr.get_reviews():
                            if r.state == "CHANGES_REQUESTED":
                                review_cycles += 1
                    except:
                        pass

                    writer.writerow({
                        "repo_name": repo.name,
                        "pr_number": pr.number,
                        "story_points": story_points,
                        "code_churn": churn,
                        "files_changed": pr.changed_files,
                        "review_cycles": review_cycles,
                        "pr_comments": pr.comments + pr.review_comments,
                        "refactoring_ratio": refactor_ratio,
                        "commit_velocity": round(churn / duration_hours, 2),
                        "velocity_sprint": velocity_sprint,
                        "active_contributors": active_contributors,
                        "stars": repo.stargazers_count,
                        "ai_mentions": ai_mentions,
                        "ai_commits": ai_commits
                    })
                    pr_collected += 1
                    print(f"  > PR #{pr.number} | SP: {story_points}", end="\r")

                repo_count += 1
                time.sleep(1)
            except Exception as e:
                print(f"\nErreur sur {repo.full_name}: {e}")

    print(f"\nTerminé ! Fichier généré : {CSV_FILE}")

if __name__ == "__main__":
    get_data()